package:
  name: rise
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.') }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - python
    - notebook >=4.2.0
  run:
    - python
    - notebook >=4.2.0

test:
  requires:
    - python
    - notebook >=4.2.0

about:
  home: https://github.com/damianavila/RISE
  license: BSD 3-Clause
  license_file: LICENSE.md
